    sudo: required
    services:
      - docker

    matrix:
        allow_failures:

    cache: bundler

    install:
        - docker build -t rock/owlapi .
        - docker run -d rock/owlapi tail -f /dev/null
        - docker ps -a

    # overwrite the default build command
    script:
        - docker run rock/owlapi /bin/bash -c "source /home/docker/rock_test/env.sh; BOOST_TEST_CATCH_SYSTEM_ERRORS=\"no\" make -C knowledge_reasoning/owlapi/build test"
