    sudo: required
    services:
      - docker

    matrix:
        allow_failures:

    cache: bundler

    install:
        - docker build -t rock/owlapi .
                --build-arg PKG_NAME="knowledge_reasoning/owlapi"
                --build-arg PKG_BRANCH="${TRAVIS_BRANCH}"
                --build-arg PKG_PULL_REQUEST="${TRAVIS_PULL_REQUEST}"

    # overwrite the default build command
    script:
        - docker run rock/owlapi /bin/bash -c "source /home/docker/rock_test/env.sh; BOOST_TEST_CATCH_SYSTEM_ERRORS=\"no\" make -C knowledge_reasoning/owlapi/build test"
